[package]
name = "cli-readme-generator-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
email_address = "0.2.9"
markdown-gen = "1.2.1"
serde =  { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
